all:
	echo Making read.
	(cd read r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: READ

	echo Making tsns_fold.
	(cd tsns_fold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TSNS_FOLD

	echo Making trig_tsns_fold.
	(cd trig_tsns_fold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TRIG_TSNS_FOLD

	echo Making print_triggered_events.
	(cd print_triggered_events r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: PRINT_TRIGGERED_EVENTS

	echo Making print_triggered_event.
	(cd print_triggered_event r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: PRINT_TRIGGERED_EVENT

	echo Making check_order.
	(cd check_order r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_ORDER

	echo Making check_final_trigger.
	(cd check_final_trigger r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_FINAL_TRIGGER

	echo Making HPGe_CC_time_difference.
	(cd HPGe_CC_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGe_CC_TIME_DIFFERENCE

	echo Making HPGe_CC_Seg_time_difference.
	(cd HPGe_CC_Seg_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGe_CC_SEG_TIME_DIFFERENCE

	echo Making HPGe_CC_Sup_time_difference.
	(cd HPGe_CC_Sup_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGe_CC_SUP_TIME_DIFFERENCE

	echo Making HPGe_CC_TIP_time_difference.
	(cd HPGe_CC_TIP_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGe_CC_TIP_TIME_DIFFERENCE

	echo Making HPGe_CC_EMMA_time_difference.
	(cd HPGe_CC_EMMA_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGe_CC_EMMA_TIME_DIFFERENCE

	echo Making TIP_time_difference.
	(cd TIP_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIP_TIME_DIFFERENCE

	echo Making TIP_EMMA_time_difference.
	(cd TIP_EMMA_time_difference r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: TIP_EMMA_TIME_DIFFERENCE

	echo Making check_HPGe_CC_Seg_map.
	(cd check_HPGe_CC_Seg_map r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_SEG_MAP

	echo Making check_HPGe_CC_gate.
	(cd check_HPGe_CC_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_GATE

	echo Making check_HPGe_CC_Seg_gate.
	(cd check_HPGe_CC_Seg_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_SEG_GATE

	echo Making check_HPGe_CC_Sup_gate.
	(cd check_HPGe_CC_Sup_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_SUP_GATE

	echo Making check_HPGe_CC_TIP_gate.
	(cd check_HPGe_CC_TIP_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_TIP_GATE

	echo Making check_HPGe_CC_EMMA_gate.
	(cd check_HPGe_CC_EMMA_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_HPGe_CC_EMMA_GATE

	echo Making check_TIP_gate.
	(cd check_TIP_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_TIP_GATE

	echo Making check_TIP_EMMA_gate.
	(cd check_TIP_EMMA_gate r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_TIP_EMMA_GATE

	echo Making tsns_fold.
	(cd tsns_fold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_TSNS_FOLD

	echo Making trig_tsns_fold.
	(cd trig_tsns_fold r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: CHECK_TRIG_TSNS_FOLD

	echo Making find_same_trig_tsns.
	(cd find_same_trig_tsns r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: FIND_SAME_TRIG_TSNS

clean:
	(cd read                         && make -is clean && cd ..)
	(cd tsns_fold                    && make -is clean && cd ..)
	(cd trig_tsns_fold               && make -is clean && cd ..)
	(cd print_triggered_events       && make -is clean && cd ..)
	(cd print_triggered_event        && make -is clean && cd ..)
	(cd check_order                  && make -is clean && cd ..)
	(cd check_final_trigger          && make -is clean && cd ..)
	(cd HPGe_CC_time_difference      && make -is clean && cd ..)
	(cd HPGe_CC_Seg_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_Sup_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_TIP_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_EMMA_time_difference && make -is clean && cd ..)
	(cd TIP_time_difference          && make -is clean && cd ..)
	(cd TIP_EMMA_time_difference     && make -is clean && cd ..)
	(cd check_HPGe_CC_Seg_map        && make -is clean && cd ..)
	(cd check_HPGe_CC_gate           && make -is clean && cd ..)
	(cd check_HPGe_CC_Seg_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_Sup_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_TIP_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_EMMA_gate      && make -is clean && cd ..)
	(cd check_TIP_gate               && make -is clean && cd ..)
	(cd check_TIP_EMMA_gate          && make -is clean && cd ..)
	(cd find_same_trig_tsns          && make -is clean && cd ..)
	rm *~

very-clean:
	(cd read                         && make -is clean && cd ..)
	(cd tsns_fold                    && make -is clean && cd ..)
	(cd trig_tsns_fold               && make -is clean && cd ..)
	(cd print_triggered_events       && make -is clean && cd ..)
	(cd print_triggered_event        && make -is clean && cd ..)
	(cd check_order                  && make -is clean && cd ..)
	(cd check_final_trigger          && make -is clean && cd ..)
	(cd HPGe_CC_time_difference      && make -is clean && cd ..)
	(cd HPGe_CC_Seg_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_Sup_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_TIP_time_difference  && make -is clean && cd ..)
	(cd HPGe_CC_EMMA_time_difference && make -is clean && cd ..)
	(cd TIP_time_difference          && make -is clean && cd ..)
	(cd TIP_EMMA_time_difference     && make -is clean && cd ..)
	(cd check_HPGe_CC_Seg_map        && make -is clean && cd ..)
	(cd check_HPGe_CC_gate           && make -is clean && cd ..)
	(cd check_HPGe_CC_Seg_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_Sup_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_TIP_gate       && make -is clean && cd ..)
	(cd check_HPGe_CC_EMMA_gate      && make -is clean && cd ..)
	(cd check_TIP_gate               && make -is clean && cd ..)
	(cd check_TIP_EMMA_gate          && make -is clean && cd ..)
	(cd find_same_trig_tsns          && make -is clean && cd ..)
	rm *~
