all:
	echo Making HPGe_CC_trigger.
	(cd HPGe_CC_trigger r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: HPGE_CC_TRIGGER

	echo Making TIG_trigger_to_Seg.
	(cd  TIG_trigger_to_Seg r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIG_trigger_to_Seg.

	echo Making TIG_trigger_to_Sup.
	(cd  TIG_trigger_to_Sup r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIG_trigger_to_Sup.

	echo Making TIG_trigger_to_TIP.
	(cd  TIG_trigger_to_TIP r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIG_trigger_to_TIP

	echo Making TIG_trigger_to_EMMA.
	(cd  TIG_trigger_to_EMMA r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIG_trigger_to_EMMA

	echo Making TIG_Trigger_tsns.
	(cd  TIG_Trigger_tsns r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIG_Trigger_tsns

	echo Making TIP_trigger.
	(cd TIP_trigger r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIP_trigger

	echo Making TIP_trigger_to_EMMA.
	(cd  TIP_trigger_to_EMMA r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIP_trigger_to_EMMA

	echo Making TIP_Trigger_tsns.
	(cd  TIP_Trigger_tsns r && make -is clean && make && make -is clean && cd ..)
	echo DONE: TIP_Trigger_tsns

	echo Making EMMA_trigger.
	(cd EMMA_trigger r && make -is clean && make && make -is clean && cd ..)
	echo DONE: EMMA_trigger

	echo Making EMMA_Trigger_tsns.
	(cd  EMMA_Trigger_tsns r && make -is clean && make && make -is clean && cd ..)
	echo DONE: EMMA_Trigger_tsns

	echo Making final_trigger.
	(cd  final_trigger r && make -is clean && make && make -is clean && cd ..)
	echo DONE: final_trigger

	echo Making clear_final_trigger.
	(cd  clear_final_trigger r && make -is clean && make && make -is clean && cd ..)
	echo DONE: clear_final_trigger

	echo Making combine.
	(cd combine r && make -is clean && make  && make -is clean && cd ..)
	echo DONE: COMBINE

	echo Making reset.
	(cd  reset && make -is clean && make && make -is clean && cd ..)
	echo DONE: reset.

	echo Making reset.
	(cd  reset && make -is clean && make && make -is clean && cd ..)
	echo DONE: reset.

	echo Making remove_tsns_bursts
	(cd  remove_tsns_bursts && make -is clean && make && make -is clean && cd ..)
	echo DONE: remove_tsns_bursts

	echo Making correct_same_trig_tsns
	(cd  correct_same_trig_tsns && make -is clean && make && make -is clean && cd ..)
	echo DONE: correct_same_trig_tsns


clean:
	(cd HPGe_CC_trigger             && make -is clean && cd ..)
	(cd TIG_trigger_to_Seg          && make -is clean && cd ..)
	(cd TIG_trigger_to_Sup          && make -is clean && cd ..)
	(cd TIG_trigger_to_TIP          && make -is clean && cd ..)
	(cd TIG_trigger_to_EMMA         && make -is clean && cd ..)
	(cd TIG_Trigger_tsns            && make -is clean && cd ..)
	(cd TIP_trigger                 && make -is clean && cd ..)
	(cd TIP_trigger_to_EMMA         && make -is clean && cd ..)
	(cd TIP_Trigger_tsns            && make -is clean && cd ..)
	(cd EMMA_trigger                && make -is clean && cd ..)
	(cd EMMA_Trigger_tsns           && make -is clean && cd ..)
	(cd final_trigger               && make -is clean && cd ..)
	(cd clear_final_trigger         && make -is clean && cd ..)
	(cd combine                     && make -is clean && cd ..)
	(cd reset                       && make -is clean && cd ..)
	(cd remove_tsns_bursts          && make -is clean && cd ..)
	(cd correct_same_trig_tsns      && make -is clean && cd ..)
	rm -f *~

very-clean:
	(cd HPGe_CC_trigger             && make -is clean && cd ..)
	(cd TIG_trigger_to_Seg          && make -is clean && cd ..)
	(cd TIG_trigger_to_Sup          && make -is clean && cd ..)
	(cd TIG_trigger_to_TIP          && make -is clean && cd ..)
	(cd TIG_trigger_to_EMMA         && make -is clean && cd ..)
	(cd TIG_Trigger_tsns            && make -is clean && cd ..)
	(cd TIP_trigger                 && make -is clean && cd ..)
	(cd TIP_trigger_to_EMMA         && make -is clean && cd ..)
	(cd TIP_Trigger_tsns            && make -is clean && cd ..)
	(cd EMMA_trigger                && make -is clean && cd ..)
	(cd EMMA_Trigger_tsns           && make -is clean && cd ..)
	(cd final_trigger               && make -is clean && cd ..)
	(cd clear_final_trigger         && make -is clean && cd ..)
	(cd combine                     && make -is clean && cd ..)
	(cd reset                       && make -is clean && cd ..)
	(cd remove_tsns_bursts          && make -is clean && cd ..)
	(cd correct_same_trig_tsns      && make -is clean && cd ..)
	rm -f *~
